import Mathlib

#check MeasurableEquiv.piFinSuccAbove
#check volume_preserving_piFinSuccAbove
#check PiLp.volume_preserving_toLp
#check PiLp.volume_preserving_ofLp
#check MeasureTheory.Measure.volume_eq_prod
#check MeasureTheory.Measure.prod_apply
#check MeasureTheory.MeasurePreserving.measure_preimage
#check EuclideanSpace.volume_ball
#check MeasureTheory.Measure.addHaar_ball
#check MeasureTheory.Measure.addHaar_ball_of_pos
#check PiLp.norm_sq_eq_sum
#check PiLp.norm_eq_sum
#check EuclideanSpace.norm_sq_eq
#check Fin.sum_univ_succ
#check Fin.insertNth
#check MeasurableEquiv.toLp
#check MeasureTheory.lintegral_const_mul
#check MeasureTheory.lintegral_mul_const
#check MeasureTheory.lintegral_indicator
#check MeasureTheory.lintegral_comp
#check MeasureTheory.MeasureTheory
#check MeasureTheory.ofReal_integral_eq_lintegral_ofReal
#check MeasureTheory.integral_pow
#check intervalIntegral.integral_pow
#check ENNReal.toReal_ofReal
#check ENNReal.ofReal_pow
#check Real.Gamma_add_one
#check Real.Gamma_pos_of_pos
